### ISSUE TITLE
Static "Mirror" build without the editor tools

### ISSUE THREAD

**Issue by nilskj** [michael/editable-website#6]
Awesome thing! I'm playing around with it a lot and I like the simplicity in it's abstractions. Would it be possible to have a static build of the site without the editor tools? As I understand we ship the whole thing with editor etc even though that stuff will only be used by the editors.

Implementation ideas
- Multiple sveltekit adapters outputs the editor plus a separate static build?
- Push the whole static build to S3 storage.
- Can we "cache" the static build awaiting the dynamic app parts somehow?
- Check if logged in in page load, async await code splitted editor functionalities if user is logged in.

I'm not sure if this is a good idea, since I quite like the "embedded" fashion and don't want the complexity of another static build. It  takes this into the direction of the other CMSs which I don't like. But I don't like shipping a lot of code for editing when only a fraction of the visitors will be able to use it anyways.

**Comment by michael** [comment]
Yeah, as you say the challenge is to avoid additional infrastructure and code branches so we don't end up with complex build/publishing workflows again. Still a "static mirror" may be interesting for high traffic websites, so I'm keen to have a solution for that at some point.

However, short-term a good first step would be `await import` so that the editor-related bits are only loaded when logged in. Would you be interested in working on a PR that adds that? :)

**Comment by nilskj** [comment]
Yes that solution sounds like the least complex and still adds value. I can give it a shot :)

**Comment by michael** [comment]
Well done! Thanks a lot.

**Comment by nilskj** [comment]
This solution is balanced with added complexity and value IMO, closing issue.
